In [100]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [101]:
data = pd.read_csv('test1.csv')

In [102]:
data.head()

   R value  L value
0        0       42
1        0       44
2        0       43
3        0       43
4        0       44

In [103]:
data.describe()

           R value      L value
count  1824.000000  1824.000000
mean     21.385417    21.980263
std      19.901679    17.687655
min       0.000000     0.000000
25%       0.000000     0.000000
50%      18.000000    25.000000
75%      44.000000    40.000000
max      52.000000    46.000000

In [104]:
R_value = data.iloc[:,0]
L_value = data.iloc[:,1]
print(R_value)
print(L_value)
L_value[27]

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
1794    20
1795    21
1796    21
1797    21
1798    21
1799    22
1800    22
1801    23
1802    23
1803    22
1804    22
1805    22
1806    21
1807    20
1808    20
1809    19
1810    18
1811    17
1812    17
1813    16
1814    16
1815    15
1816    14
1817    13
1818    11
1819    11
1820     9
1821     8
1822     7
1823     6
Name: R value, Length: 1824, dtype: int64
0       42
1       44
2       43
3       43
4       44
5       44
6       44
7       42
8       43
9       43
10      44
11      45
12      44
13      44
14      44
15      45
16      45
17      44
18      44
19      44
20      44
21      45
22      45
23      45
24      45
25      44
26      44
27      45
28      44
29      44
        ..
1794    19
1795    19
1796    19
1797    20
1798    20
1799    20
1800    19
1801    18
1802    17
1803    16
1804    16
1805    15
1806    15
1807    15
1808    12
1809    11
1810    11
1811    10
1812    10
1813    10
1814    10
1815    10
1816     9
1817     8
1818     8
1819     8
1820     7
1821     7
1822     5
1823     5
Name: L value, Length: 1824, dtype: int64

45

In [105]:
j=0
c=0
k=0
R_feature=[]
for i in range(len(R_value)):
    if R_value[i] == 0 and R_value[i+1] != 0:
        print("period start:  " ,i)
        c=c+1
        if c%2 !=0:
            j=i
            R_period=R_value[k:j]
            R_mean=np.mean(R_period)
            R_std=np.std(R_period)
            R_max=np.max(R_period)
            R_ratio=R_max/R_mean
            R_time=j-k
            feature=[R_mean,R_std,R_max,R_ratio,R_time,k,j]
            R_feature.append(feature)
            print("period:",R_period)
        if c %2 ==0:
            k=i
            R_period=R_value[j:k]
            R_mean=np.mean(R_period)
            R_std=np.std(R_period)
            R_max=np.max(R_period)
            R_ratio=R_max/R_mean
            R_time=k-j
            feature=[R_mean,R_std,R_max,R_ratio,R_time,j,k]
            R_feature.append(feature)
            print("period:",R_period)
print(R_feature[1:])

period start:   29
period: 0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
Name: R value, dtype: int64
period start:   162
period: 29      0
30      1
31      2
32      4
33      5
34      6
35      7
36      7
37     10
38     12
39     15
40     16
41     17
42     20
43     23
44     25
45     28
46     31
47     32
48     36
49     38
50     40
51     41
52     42
53     42
54     42
55     41
56     41
57     42
58     41
       ..
132     0
133     0
134     0
135     0
136     0
137     0
138     0
139     0
140     0
141     0
142     0
143     0
144     0
145     0
146     0
147     0
148     0
149     0
150     0
151     0
152     0
153     0
154     0
155     0
156     0
157     0
158     0
159     0
160     0
161     0
Name: R value, Length: 133, dtype: int64
period start:   275
period: 162     0
163     1
164     5
165     7
166     9
167    12
168    14
169    17
170    19
171    20
172    21
173    22
174    24
175    26
176    29
177    32
178    35
179    37
180    39
181    42
182    43
183    45
184    46
185    46
186    46
187    47
188    48
189    46
190    47
191    47
       ..
245     0
246     0
247     0
248     0
249     0
250     0
251     0
252     0
253     0
254     0
255     0
256     0
257     0
258     0
259     0
260     0
261     0
262     0
263     0
264     0
265     0
266     0
267     0
268     0
269     0
270     0
271     0
272     0
273     0
274     0
Name: R value, Length: 113, dtype: int64
period start:   389
period: 275     0
276     1
277     4
278     7
279    10
280    12
281    13
282    15
283    18
284    22
285    23
286    27
287    29
288    33
289    36
290    40
291    41
292    43
293    43
294    45
295    44
296    45
297    47
298    46
299    46
300    46
301    47
302    46
303    47
304    48
       ..
359     0
360     0
361     0
362     0
363     0
364     0
365     0
366     0
367     0
368     0
369     0
370     0
371     0
372     0
373     0
374     0
375     0
376     0
377     0
378     0
379     0
380     0
381     0
382     0
383     0
384     0
385     0
386     0
387     0
388     0
Name: R value, Length: 114, dtype: int64
period start:   488
period: 389     0
390     1
391     4
392     6
393     7
394     7
395     9
396    10
397    12
398    15
399    16
400    19
401    20
402    23
403    27
404    31
405    34
406    38
407    41
408    43
409    44
410    45
411    47
412    47
413    46
414    47
415    46
416    46
417    47
418    47
       ..
458     0
459     0
460     0
461     0
462     0
463     0
464     0
465     0
466     0
467     0
468     0
469     0
470     0
471     0
472     0
473     0
474     0
475     0
476     0
477     0
478     0
479     0
480     0
481     0
482     0
483     0
484     0
485     0
486     0
487     0
Name: R value, Length: 99, dtype: int64
period start:   580
period: 488     0
489     1
490     2
491     7
492     9
493    10
494    11
495    13
496    17
497    20
498    23
499    25
500    29
501    33
502    38
503    41
504    44
505    45
506    46
507    47
508    46
509    46
510    45
511    45
512    46
513    46
514    47
515    47
516    49
517    47
       ..
550     0
551     0
552     0
553     0
554     0
555     0
556     0
557     0
558     0
559     0
560     0
561     0
562     0
563     0
564     0
565     0
566     0
567     0
568     0
569     0
570     0
571     0
572     0
573     0
574     0
575     0
576     0
577     0
578     0
579     0
Name: R value, Length: 92, dtype: int64
period start:   685
period: 580     0
581     1
582     3
583     8
584    12
585    15
586    17
587    20
588    24
589    26
590    28
591    30
592    32
593    35
594    39
595    42
596    44
597    45
598    45
599    46
600    46
601    46
602    45
603    45
604    44
605    45
606    46
607    46
608    47
609    46
       ..
655     0
656     0
657     0
658     0
659     0
660     0
661     0
662     0
663     0
664     0
665     0
666     0
667     0
668     0
669     0
670     0
671     0
672     0
673     0
674     0
675     0
676     0
677     0
678     0
679     0
680     0
681     0
682     0
683     0
684     0
Name: R value, Length: 105, dtype: int64
period start:   778
period: 685     0
686     1
687     4
688     7
689    10
690    15
691    21
692    24
693    29
694    31
695    34
696    36
697    38
698    40
699    41
700    43
701    44
702    44
703    44
704    43
705    44
706    45
707    45
708    46
709    46
710    46
711    47
712    47
713    48
714    48
       ..
748     0
749     0
750     0
751     0
752     0
753     0
754     0
755     0
756     0
757     0
758     0
759     0
760     0
761     0
762     0
763     0
764     0
765     0
766     0
767     0
768     0
769     0
770     0
771     0
772     0
773     0
774     0
775     0
776     0
777     0
Name: R value, Length: 93, dtype: int64
period start:   876
period: 778     0
779     1
780     4
781    10
782    13
783    16
784    19
785    23
786    26
787    31
788    33
789    37
790    39
791    42
792    44
793    43
794    45
795    45
796    45
797    45
798    44
799    44
800    44
801    45
802    47
803    47
804    48
805    49
806    49
807    49
       ..
846     0
847     0
848     0
849     0
850     0
851     0
852     0
853     0
854     0
855     0
856     0
857     0
858     0
859     0
860     0
861     0
862     0
863     0
864     0
865     0
866     0
867     0
868     0
869     0
870     0
871     0
872     0
873     0
874     0
875     0
Name: R value, Length: 98, dtype: int64
period start:   964
period: 876     0
877     2
878     5
879     8
880    11
881    13
882    15
883    17
884    21
885    25
886    28
887    30
888    35
889    37
890    40
891    42
892    44
893    43
894    44
895    44
896    43
897    43
898    43
899    43
900    44
901    45
902    44
903    45
904    45
905    45
       ..
934     2
935     1
936     0
937     0
938     0
939     0
940     0
941     0
942     0
943     0
944     0
945     0
946     0
947     0
948     0
949     0
950     0
951     0
952     0
953     0
954     0
955     0
956     0
957     0
958     0
959     0
960     0
961     0
962     0
963     0
Name: R value, Length: 88, dtype: int64
period start:   1052
period: 964      0
965      1
966      2
967      9
968     11
969     14
970     18
971     21
972     24
973     25
974     29
975     30
976     33
977     38
978     43
979     44
980     46
981     47
982     46
983     47
984     46
985     47
986     46
987     47
988     46
989     47
990     46
991     46
992     47
993     49
        ..
1022     0
1023     0
1024     0
1025     0
1026     0
1027     0
1028     0
1029     0
1030     0
1031     0
1032     0
1033     0
1034     0
1035     0
1036     0
1037     0
1038     0
1039     0
1040     0
1041     0
1042     0
1043     0
1044     0
1045     0
1046     0
1047     0
1048     0
1049     0
1050     0
1051     0
Name: R value, Length: 88, dtype: int64
period start:   1136
period: 1052     0
1053     3
1054    10
1055    13
1056    16
1057    20
1058    23
1059    27
1060    31
1061    35
1062    36
1063    39
1064    39
1065    40
1066    41
1067    40
1068    40
1069    39
1070    39
1071    39
1072    40
1073    39
1074    41
1075    41
1076    41
1077    43
1078    42
1079    43
1080    43
1081    45
        ..
1106     8
1107     5
1108     3
1109     1
1110     0
1111     0
1112     0
1113     0
1114     0
1115     0
1116     0
1117     0
1118     0
1119     0
1120     0
1121     0
1122     0
1123     0
1124     0
1125     0
1126     0
1127     0
1128     0
1129     0
1130     0
1131     0
1132     0
1133     0
1134     0
1135     0
Name: R value, Length: 84, dtype: int64
period start:   1228
period: 1136     0
1137     1
1138     4
1139    13
1140    23
1141    26
1142    28
1143    32
1144    35
1145    38
1146    39
1147    39
1148    41
1149    42
1150    43
1151    43
1152    44
1153    45
1154    44
1155    45
1156    45
1157    46
1158    45
1159    46
1160    46
1161    47
1162    47
1163    47
1164    48
1165    50
        ..
1198     0
1199     0
1200     0
1201     0
1202     0
1203     0
1204     0
1205     0
1206     0
1207     0
1208     0
1209     0
1210     0
1211     0
1212     0
1213     0
1214     0
1215     0
1216     0
1217     0
1218     0
1219     0
1220     0
1221     0
1222     0
1223     0
1224     0
1225     0
1226     0
1227     0
Name: R value, Length: 92, dtype: int64
period start:   1312
period: 1228     0
1229     1
1230     2
1231     7
1232    10
1233    10
1234    13
1235    15
1236    17
1237    21
1238    27
1239    29
1240    33
1241    36
1242    38
1243    42
1244    44
1245    44
1246    45
1247    44
1248    45
1249    45
1250    44
1251    45
1252    44
1253    44
1254    46
1255    46
1256    46
1257    48
        ..
1282     4
1283     1
1284     1
1285     1
1286     0
1287     0
1288     0
1289     0
1290     0
1291     0
1292     0
1293     0
1294     0
1295     0
1296     0
1297     0
1298     0
1299     0
1300     0
1301     0
1302     0
1303     0
1304     0
1305     0
1306     0
1307     0
1308     0
1309     0
1310     0
1311     0
Name: R value, Length: 84, dtype: int64
period start:   1413
period: 1312     0
1313     1
1314     7
1315    14
1316    15
1317    18
1318    21
1319    24
1320    27
1321    30
1322    31
1323    34
1324    37
1325    39
1326    42
1327    43
1328    44
1329    43
1330    43
1331    42
1332    43
1333    42
1334    42
1335    42
1336    42
1337    42
1338    44
1339    43
1340    44
1341    45
        ..
1383     0
1384     0
1385     0
1386     0
1387     0
1388     0
1389     0
1390     0
1391     0
1392     0
1393     0
1394     0
1395     0
1396     0
1397     0
1398     0
1399     0
1400     0
1401     0
1402     0
1403     0
1404     0
1405     0
1406     0
1407     0
1408     0
1409     0
1410     0
1411     0
1412     0
Name: R value, Length: 101, dtype: int64
period start:   1502
period: 1413     0
1414     1
1415     3
1416     8
1417    11
1418    15
1419    17
1420    20
1421    23
1422    28
1423    29
1424    31
1425    34
1426    35
1427    38
1428    40
1429    41
1430    42
1431    41
1432    40
1433    41
1434    42
1435    42
1436    43
1437    43
1438    44
1439    44
1440    44
1441    45
1442    45
        ..
1472     7
1473     5
1474     2
1475     1
1476     0
1477     0
1478     0
1479     0
1480     0
1481     0
1482     0
1483     0
1484     0
1485     0
1486     0
1487     0
1488     0
1489     0
1490     0
1491     0
1492     0
1493     0
1494     0
1495     0
1496     0
1497     0
1498     0
1499     0
1500     0
1501     0
Name: R value, Length: 89, dtype: int64
period start:   1575
period: 1502     0
1503     1
1504     3
1505    13
1506    18
1507    23
1508    24
1509    29
1510    34
1511    37
1512    39
1513    40
1514    41
1515    44
1516    44
1517    44
1518    45
1519    44
1520    44
1521    45
1522    44
1523    46
1524    46
1525    46
1526    47
1527    47
1528    47
1529    48
1530    48
1531    49
        ..
1545     7
1546     4
1547     2
1548     1
1549     1
1550     1
1551     0
1552     0
1553     0
1554     0
1555     0
1556     0
1557     0
1558     0
1559     0
1560     0
1561     0
1562     0
1563     0
1564     0
1565     0
1566     0
1567     0
1568     0
1569     0
1570     0
1571     0
1572     0
1573     0
1574     0
Name: R value, Length: 73, dtype: int64
period start:   1625
period: 1575     0
1576     1
1577     7
1578    28
1579    33
1580    35
1581    42
1582    46
1583    48
1584    48
1585    49
1586    47
1587    45
1588    45
1589    43
1590    41
1591    40
1592    39
1593    40
1594    40
1595    41
1596    43
1597    44
1598    46
1599    46
1600    48
1601    49
1602    49
1603    50
1604    50
1605    49
1606    49
1607    48
1608    47
1609    44
1610    42
1611    39
1612    33
1613    26
1614    19
1615    12
1616     8
1617     4
1618     2
1619     1
1620     1
1621     1
1622     1
1623     0
1624     0
Name: R value, dtype: int64
period start:   1755
period: 1625     0
1626     1
1627     9
1628     8
1629     4
1630     9
1631    13
1632    19
1633    25
1634    31
1635    35
1636    39
1637    41
1638    43
1639    44
1640    43
1641    43
1642    43
1643    42
1644    41
1645    43
1646    40
1647    38
1648    32
1649    29
1650    26
1651    23
1652    19
1653    18
1654    16
        ..
1725     9
1726    10
1727    13
1728    14
1729    14
1730    15
1731    16
1732    16
1733    16
1734    16
1735    16
1736    16
1737    16
1738    15
1739    13
1740    13
1741    11
1742    10
1743     9
1744     8
1745     7
1746     5
1747     4
1748     3
1749     2
1750     1
1751     1
1752     1
1753     0
1754     0
Name: R value, Length: 130, dtype: int64
[[22.406015037593985, 18.84644622330411, 47, 2.0976510067114096, 133, 29, 162], [23.36283185840708, 20.632074843179517, 50, 2.140151515151515, 113, 162, 275], [21.29824561403509, 20.60443225379134, 51, 2.3945634266886326, 114, 275, 389], [18.707070707070706, 20.559473976907125, 51, 2.726241900647948, 99, 389, 488], [19.72826086956522, 20.90199868790874, 52, 2.6358126721763084, 92, 488, 580], [23.485714285714284, 20.954878639006974, 49, 2.0863746958637472, 105, 580, 685], [21.118279569892472, 20.16589768143696, 49, 2.3202647657841142, 93, 685, 778], [23.275510204081634, 21.428466957957205, 51, 2.1911442349846557, 98, 778, 876], [23.28409090909091, 20.484444687946848, 48, 2.061493411420205, 88, 876, 964], [20.0, 20.890950628964163, 52, 2.6, 88, 964, 1052], [23.19047619047619, 19.220819683277092, 45, 1.9404517453798769, 84, 1052, 1136], [24.347826086956523, 21.821626081466043, 52, 2.1357142857142857, 92, 1136, 1228], [23.107142857142858, 21.0780962009329, 50, 2.1638330757341575, 84, 1228, 1312], [23.128712871287128, 20.256114278657495, 48, 2.0753424657534247, 101, 1312, 1413], [23.59550561797753, 19.769298124613723, 47, 1.9919047619047618, 89, 1413, 1502], [21.506849315068493, 20.68890463520705, 50, 2.3248407643312103, 73, 1502, 1575], [32.18, 18.475594713026155, 50, 1.5537600994406464, 50, 1575, 1625], [15.084615384615384, 12.700717493593457, 44, 2.9168791432942376, 130, 1625, 1755]]

C:\Users\11379\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app

In [106]:
t=pd.DataFrame(R_feature[1:4])
print(t)
R_bvaluemean=np.mean(t.iloc[0:2,0])
R_bstdmean=np.mean(t.iloc[0:2,1])
R_bmaxmean=np.mean(t.iloc[0:2,2])
R_bratiomean=np.mean(t.iloc[0:2,3])
R_bperiodmean=np.mean(t.iloc[0:2,4])
R_analysis=[]
b_analysis=[R_bvaluemean,R_bstdmean,R_bmaxmean,R_bratiomean,R_bperiodmean]
R_analysis.append(b_analysis)
print("beginning period:",R_analysis)

q=pd.DataFrame(R_feature[5:15])
print(q)
R_svaluemean=np.mean(t.iloc[0:9,0])
R_sstdmean=np.mean(t.iloc[0:9,1])
R_smaxmean=np.mean(t.iloc[0:9,2])
R_sratiomean=np.mean(t.iloc[0:9,3])
R_speriodmean=np.mean(t.iloc[0:9,4])
s_analysis=[R_svaluemean,R_sstdmean,R_smaxmean,R_sratiomean,R_speriodmean]
R_analysis.append(s_analysis)
print("beginning and stable period: ",R_analysis)

           0          1   2         3    4    5    6
0  22.406015  18.846446  47  2.097651  133   29  162
1  23.362832  20.632075  50  2.140152  113  162  275
2  21.298246  20.604432  51  2.394563  114  275  389
beginning period: [[22.884423448000533, 19.73926053324181, 48.5, 2.1189012609314624, 123.0]]
           0          1   2         3    4     5     6
0  19.728261  20.901999  52  2.635813   92   488   580
1  23.485714  20.954879  49  2.086375  105   580   685
2  21.118280  20.165898  49  2.320265   93   685   778
3  23.275510  21.428467  51  2.191144   98   778   876
4  23.284091  20.484445  48  2.061493   88   876   964
5  20.000000  20.890951  52  2.600000   88   964  1052
6  23.190476  19.220820  45  1.940452   84  1052  1136
7  24.347826  21.821626  52  2.135714   92  1136  1228
8  23.107143  21.078096  50  2.163833   84  1228  1312
9  23.128713  20.256114  48  2.075342  101  1312  1413
beginning and stable period:  [[22.884423448000533, 19.73926053324181, 48.5, 2.1189012609314624, 123.0], [22.355697503345386, 20.027651106758324, 49.333333333333336, 2.210788649517186, 120.0]]

In [164]:
R_ratio=pd.DataFrame(R_analysis)
print(R_ratio)
R_bsvalue=R_ratio.iloc[0,0]/R_ratio.iloc[1,0]
R_bsstd=R_ratio.iloc[0,1]/R_ratio.iloc[1,1]
R_bsmax=R_ratio.iloc[0,2]/R_ratio.iloc[1,2]
R_bsratio=R_ratio.iloc[0,3]/R_ratio.iloc[1,3]
R_bsperiod=R_ratio.iloc[0,4]/R_ratio.iloc[1,4]
R_bs=[R_bsvalue,R_bsstd,R_bsmax,R_bsratio,R_bsperiod]
R_bs=pd.DataFrame(R_bs,index=['R_bsmean','R_bsstd','R_bsmax','R_bsratio','R_bsperiod'])
print(R_bs.T)

           0          1          2         3      4
0  22.884423  19.739261  48.500000  2.118901  123.0
1  22.355698  20.027651  49.333333  2.210789  120.0
   R_bsmean  R_bsstd   R_bsmax  R_bsratio  R_bsperiod
0  1.023651   0.9856  0.983108   0.958437       1.025

In [165]:
df1=pd.DataFrame(R_feature[1:],columns=["R_mean",'R_std','R_max','R_ratio','R_period','R_start','R_end'])
df2=pd.DataFrame(R_bs.T)
print(df2)
R_file = pd.concat([df1,df2],axis=1)
R_file = pd.DataFrame(R_file)
print(R_file)

   R_bsmean  R_bsstd   R_bsmax  R_bsratio  R_bsperiod
0  1.023651   0.9856  0.983108   0.958437       1.025
       R_mean      R_std  R_max   R_ratio  R_period  R_start  R_end  R_bsmean  \
0   22.406015  18.846446     47  2.097651       133       29    162  1.023651
1   23.362832  20.632075     50  2.140152       113      162    275       NaN
2   21.298246  20.604432     51  2.394563       114      275    389       NaN
3   18.707071  20.559474     51  2.726242        99      389    488       NaN
4   19.728261  20.901999     52  2.635813        92      488    580       NaN
5   23.485714  20.954879     49  2.086375       105      580    685       NaN
6   21.118280  20.165898     49  2.320265        93      685    778       NaN
7   23.275510  21.428467     51  2.191144        98      778    876       NaN
8   23.284091  20.484445     48  2.061493        88      876    964       NaN
9   20.000000  20.890951     52  2.600000        88      964   1052       NaN
10  23.190476  19.220820     45  1.940452        84     1052   1136       NaN
11  24.347826  21.821626     52  2.135714        92     1136   1228       NaN
12  23.107143  21.078096     50  2.163833        84     1228   1312       NaN
13  23.128713  20.256114     48  2.075342       101     1312   1413       NaN
14  23.595506  19.769298     47  1.991905        89     1413   1502       NaN
15  21.506849  20.688905     50  2.324841        73     1502   1575       NaN
16  32.180000  18.475595     50  1.553760        50     1575   1625       NaN
17  15.084615  12.700717     44  2.916879       130     1625   1755       NaN

    R_bsstd   R_bsmax  R_bsratio  R_bsperiod
0    0.9856  0.983108   0.958437       1.025
1       NaN       NaN        NaN         NaN
2       NaN       NaN        NaN         NaN
3       NaN       NaN        NaN         NaN
4       NaN       NaN        NaN         NaN
5       NaN       NaN        NaN         NaN
6       NaN       NaN        NaN         NaN
7       NaN       NaN        NaN         NaN
8       NaN       NaN        NaN         NaN
9       NaN       NaN        NaN         NaN
10      NaN       NaN        NaN         NaN
11      NaN       NaN        NaN         NaN
12      NaN       NaN        NaN         NaN
13      NaN       NaN        NaN         NaN
14      NaN       NaN        NaN         NaN
15      NaN       NaN        NaN         NaN
16      NaN       NaN        NaN         NaN
17      NaN       NaN        NaN         NaN

In [166]:
R_file.to_csv('resultR.csv',columns=["R_mean",'R_std','R_max','R_ratio','R_period','R_start','R_end','R_bsmean','R_bsstd','R_bsmax','R_bsratio','R_bsperiod'],index=False,sep=',')

            0         0
0   22.406015  1.023651
1   23.362832       NaN
2   21.298246       NaN
3   18.707071       NaN
4   19.728261       NaN
5   23.485714       NaN
6   21.118280       NaN
7   23.275510       NaN
8   23.284091       NaN
9   20.000000       NaN
10  23.190476       NaN
11  24.347826       NaN
12  23.107143       NaN
13  23.128713       NaN
14  23.595506       NaN
15  21.506849       NaN
16  32.180000       NaN
17  15.084615       NaN
            1       1
0   18.846446  0.9856
1   20.632075     NaN
2   20.604432     NaN
3   20.559474     NaN
4   20.901999     NaN
5   20.954879     NaN
6   20.165898     NaN
7   21.428467     NaN
8   20.484445     NaN
9   20.890951     NaN
10  19.220820     NaN
11  21.821626     NaN
12  21.078096     NaN
13  20.256114     NaN
14  19.769298     NaN
15  20.688905     NaN
16  18.475595     NaN
17  12.700717     NaN
     2         2
0   47  0.983108
1   50       NaN
2   51       NaN
3   51       NaN
4   52       NaN
5   49       NaN
6   49       NaN
7   51       NaN
8   48       NaN
9   52       NaN
10  45       NaN
11  52       NaN
12  50       NaN
13  48       NaN
14  47       NaN
15  50       NaN
16  50       NaN
17  44       NaN
           3         3
0   2.097651  0.958437
1   2.140152       NaN
2   2.394563       NaN
3   2.726242       NaN
4   2.635813       NaN
5   2.086375       NaN
6   2.320265       NaN
7   2.191144       NaN
8   2.061493       NaN
9   2.600000       NaN
10  1.940452       NaN
11  2.135714       NaN
12  2.163833       NaN
13  2.075342       NaN
14  1.991905       NaN
15  2.324841       NaN
16  1.553760       NaN
17  2.916879       NaN
      4      4
0   133  1.025
1   113    NaN
2   114    NaN
3    99    NaN
4    92    NaN
5   105    NaN
6    93    NaN
7    98    NaN
8    88    NaN
9    88    NaN
10   84    NaN
11   92    NaN
12   84    NaN
13  101    NaN
14   89    NaN
15   73    NaN
16   50    NaN
17  130    NaN
0       29
1      162
2      275
3      389
4      488
5      580
6      685
7      778
8      876
9      964
10    1052
11    1136
12    1228
13    1312
14    1413
15    1502
16    1575
17    1625
Name: 5, dtype: int64
0      162
1      275
2      389
3      488
4      580
5      685
6      778
7      876
8      964
9     1052
10    1136
11    1228
12    1312
13    1413
14    1502
15    1575
16    1625
17    1755
Name: 6, dtype: int64

KeyError: 7